### PR TITLE
Add lxml to C-extension whitelist.

### PR DESCRIPTION
**Pull request by jcdyer**

### CODE REVIEW

**Comment by sarina** [comment]
When this is merged, I'd love to see the update to edx-platform that removes the `# pylint: disable: no-member` pragmas from instances of `etree.` - there are certainly a lot of them in the codebase, and I often see people mindlessly copying unneeded pragmas from stale areas of the codebase.

**Comment by nedbat** [comment]
@jcdyer thanks.  To get this into edx-platform, you'll have to also bump the version number in setup.py

**Comment by jcdyer** [comment]
To be followed up with: https://openedx.atlassian.net/browse/TOOLS-124, as requested by @sarina

**Comment by jcdyer** [comment]
@sarina @nedbat, since you guys are here already, can I ask you to be my reviewers?

**Comment by sarina** [comment]
:+1:

**Comment by jcdyer** [comment]
@nedbat: Do you see any risk in changing this to allow all C extensions to be imported?  It seems safe enough to me, but I might be missing something.

**Comment by nedbat** [comment]
@jcdyer it would be very useful to see the diff of the pylint reports after setting this.

**Comment by jcdyer** [comment]
[pylint-before.txt](https://github.com/edx/edx-lint/files/24587/pylint-before.txt)
[pylint-after.txt](https://github.com/edx/edx-lint/files/24586/pylint-after.txt)
[pylint-diff.txt](https://github.com/edx/edx-lint/files/24588/pylint-diff.txt)

All lines in the diff are from either lxml or numpy.  Seems like a win.  I'll use the unsafe-load-any-extension version.

**Comment by nedbat** [comment]
@jcdyer very nice, 300 violations nuked from orbit!  Merge this, and then we can make the pull request against edx-platform.

**Comment by jcdyer** [comment]
Merged.

**Pull request merged**
