### PR TITLE
Checker for tests inheriting from tests

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@cpennington you like?

**Comment by nedbat** [comment]
FYI, this checker finds these problems in edx-platform:
```
cms/djangoapps/contentstore/tests/test_courseware_index.py:1445: [E7603(test-inherits-tests), GroupConfigurationSearchSplit] test class GroupConfigurationSearchSplit inherits tests from GroupConfigurationSearchMongo
cms/djangoapps/contentstore/tests/test_transcripts_utils.py:347: [E7603(test-inherits-tests), TestGenerateSubsFromSource] test class TestGenerateSubsFromSource inherits tests from TestDownloadYoutubeSubs
cms/djangoapps/contentstore/tests/test_transcripts_utils.py:418: [E7603(test-inherits-tests), TestGenerateSrtFromSjson] test class TestGenerateSrtFromSjson inherits tests from TestDownloadYoutubeSubs
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:239: [E7603(test-inherits-tests), GettextTest] test class GettextTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:244: [E7603(test-inherits-tests), PgettextTest] test class PgettextTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:255: [E7603(test-inherits-tests), NgettextTest] test class NgettextTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:266: [E7603(test-inherits-tests), NpgettextTest] test class NpgettextTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:276: [E7603(test-inherits-tests), NpgettextPluralTest] test class NpgettextPluralTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:280: [E7603(test-inherits-tests), NgettextPluralTest] test class NgettextPluralTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:284: [E7603(test-inherits-tests), GettextNoopTest] test class GettextNoopTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:289: [E7603(test-inherits-tests), UgettextNoopTest] test class UgettextNoopTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:294: [E7603(test-inherits-tests), UngettextTest] test class UngettextTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:299: [E7603(test-inherits-tests), UngettextPluralTest] test class UngettextPluralTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:303: [E7603(test-inherits-tests), GettextLazyTest] test class GettextLazyTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:308: [E7603(test-inherits-tests), UgettextLazyTest] test class UgettextLazyTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:313: [E7603(test-inherits-tests), PgettextLazyTest] test class PgettextLazyTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:318: [E7603(test-inherits-tests), NgettextLazyTest] test class NgettextLazyTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:323: [E7603(test-inherits-tests), NpgettextLazyTest] test class NpgettextLazyTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:328: [E7603(test-inherits-tests), NpgettextLazyPluralTest] test class NpgettextLazyPluralTest inherits tests from UgettextTest
common/djangoapps/monkey_patch/tests/test_django_utils_translation.py:332: [E7603(test-inherits-tests), UngettextLazyTest] test class UngettextLazyTest inherits tests from UgettextTest
common/djangoapps/third_party_auth/tests/specs/base.py:735: [E7603(test-inherits-tests), Oauth2IntegrationTest] test class Oauth2IntegrationTest inherits tests from IntegrationTest
common/djangoapps/third_party_auth/tests/specs/test_google.py:6: [E7603(test-inherits-tests), GoogleOauth2IntegrationTest] test class GoogleOauth2IntegrationTest inherits tests from IntegrationTest
common/djangoapps/third_party_auth/tests/specs/test_linkedin.py:6: [E7603(test-inherits-tests), LinkedInOauth2IntegrationTest] test class LinkedInOauth2IntegrationTest inherits tests from IntegrationTest
common/lib/xmodule/xmodule/modulestore/tests/test_mongo.py:762: [E7603(test-inherits-tests), TestMongoModuleStoreWithNoAssetCollection] test class TestMongoModuleStoreWithNoAssetCollection inherits tests from TestMongoModuleStore
common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore_bulk_operations.py:283: [E7603(test-inherits-tests), TestBulkWriteMixinClosedAfterPrevTransaction] test class TestBulkWriteMixinClosedAfterPrevTransaction inherits tests from TestBulkWriteMixinClosed
common/lib/xmodule/xmodule/modulestore/tests/test_split_modulestore_bulk_operations.py:710: [E7603(test-inherits-tests), TestBulkWriteMixinOpenAfterPrevTransaction] test class TestBulkWriteMixinOpenAfterPrevTransaction inherits tests from TestBulkWriteMixinOpen
lms/djangoapps/courseware/tests/test_video_handlers.py:192: [E7603(test-inherits-tests), TestTranscriptAvailableTranslationsDispatch] test class TestTranscriptAvailableTranslationsDispatch inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_handlers.py:252: [E7603(test-inherits-tests), TestTranscriptAvailableTranslationsBumperDispatch] test class TestTranscriptAvailableTranslationsBumperDispatch inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_handlers.py:310: [E7603(test-inherits-tests), TestTranscriptDownloadDispatch] test class TestTranscriptDownloadDispatch inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_handlers.py:375: [E7603(test-inherits-tests), TestTranscriptTranslationGetDispatch] test class TestTranscriptTranslationGetDispatch inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_handlers.py:607: [E7603(test-inherits-tests), TestStudioTranscriptTranslationGetDispatch] test class TestStudioTranscriptTranslationGetDispatch inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_handlers.py:665: [E7603(test-inherits-tests), TestStudioTranscriptTranslationPostDispatch] test class TestStudioTranscriptTranslationPostDispatch inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_handlers.py:726: [E7603(test-inherits-tests), TestGetTranscript] test class TestGetTranscript inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_mongo.py:30: [E7603(test-inherits-tests), TestVideoYouTube] test class TestVideoYouTube inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_mongo.py:91: [E7603(test-inherits-tests), TestVideoNonYouTube] test class TestVideoNonYouTube inherits tests from TestVideo
lms/djangoapps/courseware/tests/test_video_mongo.py:1091: [E7603(test-inherits-tests), TestVideoWithBumper] test class TestVideoWithBumper inherits tests from TestVideo
lms/djangoapps/instructor/tests/test_spoc_gradebook.py:87: [E7603(test-inherits-tests), TestDefaultGradingPolicy] test class TestDefaultGradingPolicy inherits tests from TestGradebook
lms/djangoapps/instructor/tests/test_spoc_gradebook.py:113: [E7603(test-inherits-tests), TestLetterCutoffPolicy] test class TestLetterCutoffPolicy inherits tests from TestGradebook
lms/lib/courseware_search/test/test_lms_filter_generator.py:155: [E7603(test-inherits-tests), LmsSearchFilterGeneratorGroupsTestCase] test class LmsSearchFilterGeneratorGroupsTestCase inherits tests from LmsSearchFilterGeneratorTestCase
openedx/core/lib/api/tests/test_authentication.py:24: [E7603(test-inherits-tests), OAuth2AuthenticationAllowInactiveUserTestCase] test class OAuth2AuthenticationAllowInactiveUserTestCase inherits tests from OAuth2Tests
openedx/tests/external/test_recommender.py:413: [E7603(test-inherits-tests), TestRecommenderVoteWithResources] test class TestRecommenderVoteWithResources inherits tests from TestRecommenderWithResources
openedx/tests/external/test_recommender.py:531: [E7603(test-inherits-tests), TestRecommenderStaffFeedbackWithResources] test class TestRecommenderStaffFeedbackWithResources inherits tests from TestRecommenderWithResources
```

**Comment by nedbat** [comment]
@cpennington if you won't get to it, maybe we shouldn't be sticklers for review?

**Comment by cpennington** [comment]
:+1:

**Pull request merged**
