### PR TITLE
fix typo in warning comment

### PR DESCRIPTION
**Pull request by pwnage101**
the generated pylintrc for this repo checks out:
```
% python -m edx_lint check pylintrc
Checking existing copy of pylintrc
Your copy of pylintrc is good
```

### CODE REVIEW

**Comment by nedbat** [comment]
:+1: Merge it!

**Comment by pwnage101** [comment]
@nedbat I just changed this from an FYI PR to an actual PR.  Just learned about the hash and decided to regenerate this repo's pylintrc.

**Comment by nedbat** [comment]
What is an FYI pr?

**Comment by pwnage101** [comment]
Ah, I was just going to push the PR without seeking review because it seemed to straightforward (known as an FYI PR (as far as I know).  Now it isn't seeming so straightforward to me because of things that get hashed.

**Comment by nedbat** [comment]
The hash is fine, and the fix is correct, I'm merging it :)

**Pull request merged**
