### PR TITLE
fix: remove pluggy constraint 

### PR DESCRIPTION
**Pull request by ghassanmas**
Pytest have released 6.2.5 two days ago: release note : https://docs.pytest.org/en/6.2.x/changelog.html#pytest-6-2-5-2021-08-29

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ghassanmas! I've created [OSPR-6008](https://openedx.atlassian.net/browse/OSPR-6008) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ghassanmas** [comment]
Here is where the `make upgrate` is being breaking at this branch https://github.com/edx/xblock-in-video-quiz/pull/24, 
Here is the expected output error

**Comment by nedbat** [comment]
I ran a "make upgrade", and it succeeded without conflicts.

**Review by nedbat — APPROVED** [review]

**Comment by ghassanmas** [comment]
@nedbat all good, thank you for the quick response 🙏

**Comment by natabene** [comment]
@ghassanmas Thank you for your contribution!

**Comment by edx-webhook** [comment]
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-lint&entry.867055334=https://github.com/edx/edx-lint/pull/189&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2021-09-01+10:43&entry.1917517419=2021-09-01+15:18&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
