### PR TITLE
INCR-4 upgrade click log to 0.3.2

### PR DESCRIPTION
**Pull request by pjcrouse**
Please provide a new release of edx-lint to be made once it is merged.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pjcrouse! I've created [OSPR-2825](https://openedx.atlassian.net/browse/OSPR-2825) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@pjcrouse  Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@pjcrouse  Have you had a chance to sign contributors agreement? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@pjcrouse We have not heard from you for a while, so I am closing this request. Should you decide to pursue this again, please feel free to re-open this PR.

**Comment by edx-webhook** [comment]
@pjcrouse Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-lint&entry.867055334=https://github.com/edx/edx-lint/pull/62&entry.1484655318=https://github.com/pjcrouse&entry.752974735=2018-08-02+00:47&entry.1917517419=2019-01-04+18:09&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
