### PR TITLE
Ned/fix pylint violations

### PR DESCRIPTION
**Pull request by nedbat**
Run pylint in a real way, and clean up all the pylint violations.

### CODE REVIEW

**Comment by nedbat** [comment]
@clintonb @cpennington Run pylint in travis, and fix all the violations.

**Comment by cpennington** [comment]
:+1:

**Comment by cpennington** [comment]
Should we be contributing all of these checks upstream to pylint?

**Comment by clintonb** [comment]
:+1:

**Comment by nedbat** [comment]
I've started informal discussions with the pylint maintainers about taking these checkers.  I'm more interested in them getting their code to work properly with edx-platform :)

**Pull request merged**
