### PR TITLE
Sarina/ignore parseoption docstring

### PR DESCRIPTION
**Pull request by sarina**
@cpennington or @nedbat or @feanil

### CODE REVIEW

**Comment by feanil** [comment]
:+1:  but how can I be sure without a travis build?

**Comment by nedbat** [comment]
I don't know what `parse_options` is, why doesn't it deserve a docstring?  It's defined once in edx-platform, in capa/inputtypes.py:OptionInput.

**Comment by sarina** [comment]
Its used in management commands to parse options given. It seems to have a
straightforward enough name ro not require a docstring. But if not I'll
just disable the warning explicitly or write stupid docstrings

**Comment by nedbat** [comment]
Hmm, why do none of the management commands in edx-platform have this method? What drew your attention to it?

**Comment by sarina** [comment]
Fixing up Carlos's code. If it's not a generic pattern, close this PR and
I'll write dumb docstrings.

**Comment by nedbat** [comment]
My concern about this is that "parse_options" is kind of a generic name that is not necessarily a management command method.  The only current use of the name in edx-platform is not in a management command, for example.  I'd rather be conservative and require the docstring.

**Pull request closed without merging**
